# Generated by Django 5.2.1 on 2025-07-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='voter',
        ),
    ]
